
title: Ahmad Moustapha
url: 'http://mouse-trap.github.io'
#baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Ahmad Moustapha
tagline: Developer & Researcher
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: ahmad.m.moustapha@gmail.com
phone: 71 138 669
#website: blog.webjeda.com #do not add http://
linkedin: ahmad-moustapha
github: mouse-trap
#twitter: '@twittername'

